Upgraded ANF SDK to latest version
Azure-Samples/netappfiles-dotnetcore-crr-sdk-sample pull request #6
Opened 2021-09-08 03:46 UTC by AdelGhabboun

1. Upgraded Azure Netapp files SDK to latest 1.13.0
2. Upgraded .NET Framework to .NET 5.0

2021-09-08 08:59 UTC, hildurhodd approved these changes
LGTM

2021-09-15 18:35 UTC, paulomarquesc commented on CHANGELOG.md
>  # 1.0.0 (2019-10-09)
Needs to be updated

2021-09-15 18:37 UTC, paulomarquesc requested changes
:clock1:

2021-09-15 20:57 UTC, paulomarquesc approved these changes
:shipit:

2021-09-15 21:06 UTC, merged